### ISSUE TITLE
wpf

### ISSUE THREAD

**Issue by priyamalar** [Kinect/tutorial#3]
Shall we run the hand cursor app in wpf? Do you help me how the code was build in wpf? Do you have separate code for hand cursor on wpf?

**Comment by benlower** [comment]
@priyamalar sorry but the tutorial is only available for C#/WinRT right now.  please check the "Controls Basics - WPF" sample that comes with our SDK and you will see examples of how to use hand cursor in WPF.

**Comment by priyamalar** [comment]
ok thanks
