### ISSUE TITLE
Lab 14 - Tracking Strategies

### ISSUE THREAD

**Issue by Nassobi** [Kinect/tutorial#36]
I need help in lab 14 - can I get the contact of the this tutorial developer ?

**Comment by DrNeil** [comment]
Nassobi, what do you need ?

**Comment by Nassobi** [comment]
Hello Dr.Neil.

I followed with the previous labs and the source Visual Studio applications were provided so it is clear where the libraries are coming from, but in lab 14, there is no project files (just codes without libraries) , and I do not know how to use them. I tried in different ways but I always get errors. I want to track people by Kinect 2, find the distance for each one from the kinect and also identify who came first and second. I will appreciate it if you can send me the source visual studio project of lab 14.

**Comment by DrNeil** [comment]
Hi, as stated in the lab text:
_This lab does not include much code, but instead offers insight into the design of applications with NUIs(Natural User Interfaces) such as you might create for a Kinect 2 solutions. This lab includes a discussion of the limitations and advantages of each tracking method._ 

There is no project for this lab, it assumes you have completed the other labs and offers some ideas to help you improve your application. 
If you have completed the labs then you understand how the Kinect product can be used to track people and measure distance. 
The rest is up to you.
