### ISSUE TITLE
Incompatible with VS 2017 Enterprise version

### ISSUE THREAD

**Issue by bingcheng45** [Kinect/tutorial#37]
Hi there!
currentl when i tried to run the kinect2Sample code on the latest version of visual studio 2017, i am facing this incompatible issue.
I am currently running on windows 10.
Is there a fix to this incompatibility? 
I have tried open as adminstrator, have also tried modifying the projectypeguids and other solutions online and they have yet to work.
Really looking forward to following your tutorial! :D

![image](https://cloud.githubusercontent.com/assets/12640713/26185487/dcc363b0-3bbd-11e7-9338-2f46ec82db04.png)

**Comment by DrNeil** [comment]
Hi, these labs were built for Windows 8.1 as stated on the [tutorial page](http://kinect.github.io/tutorial/) 
_The Hands On Labs to complete a sample application for Windows 8.1 and the Kinect 2 for Windows_

For Windows 10 you should look at the latest Kinect documentation for UWP apps.

**Comment by bingcheng45** [comment]
Is there kinect documentation for WPF as I'm currently working on a project to integrate gestures on a WPF project

**Comment by DrNeil** [comment]
[https://developer.microsoft.com/en-us/windows/kinect](https://developer.microsoft.com/en-us/windows/kinect
)
everything you need including the SDK and WPF samples.

**Comment by bingcheng45** [comment]
Have already looked into that, but find it hard to implement discrete gesture.
Thanks for the quick responds!
