### ISSUE TITLE
Lab 12: Gesture Builder

### ISSUE THREAD

**Issue by AfzaalLucky** [Kinect/tutorial#5]
Lab 12: Gesture Builder is not running please help. 
All other lab codes are running correctly, but gesture builder code is not displaying.

**Comment by DrNeil** [comment]
Hi, please will you provide some more information about the issue you are seeing? 
Have you followed the steps in the hands on lab document ?

**Comment by ghost** [comment]
New issue opened with more detail from the same person. Closing this as duplicate

**Comment by AfzaalLucky** [comment]
Thanks
My problem is solved

_Regards : *
*Muhammad Afzal_

_Eng.: BS (IT)_

_Cell.#: +92-307_2007747_
