### ISSUE TITLE
Lab 3 typos

### ISSUE THREAD

**Issue by Derived42** [Kinect/tutorial#7]
I noticed in the lab write up that you say the application should bring up the infrared display after all the coding.  However, in the code you've set the DEFAULT_DISPLAYFRAMETYPE = DisplayFrametype.Color.  

Might cause some confusion.

**Comment by jesse-nsquared** [comment]
Hi Derived42,

Are you referring to the Color Lab?
At step 8 it says:
"Build and Run the application to make sure there are no errors. The application should show the infrared frame as in the previous lab."

I've just changed it to:
"Build and Run the application to make sure there are no errors. The application should show the new color frame as it is set to the DEFAULT_DISPLAYFRAMETYPE."

And also changed the wording later on to switch feeds.

Thanks for finding this!
